on:
  push:
    branches:
      - master
  pull_request:
name: CI
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest-large
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - name: Test parsing
        run: gotestsum -f standard-verbose
  lint:
    name: Lint
    runs-on: ubuntu-latest-large
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - name: golangci-lint
        run: golangci-lint run
